name: Test Github Actions
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
      - name: Welcome
        run: echo "Welcome"
      
