name: Test Github Actions
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
      - name: Welcome
        run: echo "Welcome"
  test1:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Hello World
        run: echo "Hello World"
      - name: Welcome
        run: echo "Welcome"
      
